name: Build and Run Docker Image

# This makes the workflow trigger only when manually initiated
on:
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t server .

      - name: Run Docker container
        run: |
          docker run --env-file .env \
            -e GIT_USER=${{ secrets.GIT_USER }} \
            -e PLAYIT_DOCKER_KEY=${{ secrets.PLAYIT_DOCKER_KEY }} \
            --rm server
